### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by KydZombie** [ArtpokeBr/Pluma-a-Journey-to-the-Future#37]
A lot of the early game content tweaker items are missing textures, as well as some others.
Full list of everything I can see:
- Mason Felsic, Mafic, Mixed, and Plain Bricks
- Obsidian Electrode
- Blank Shape Card
- Unprepared Space Boots
- Sky Stone Doped Boule
- Unfired Porcelain Brick
- Seared Plate
- Salted Hide
- Menril Crystal

![2023-01-02_18 33 28](https://user-images.githubusercontent.com/65704439/210284966-90d2d052-eefb-4bba-a5ff-2f67024014a5.png)

![Screenshot from 2023-01-02 18-37-20](https://user-images.githubusercontent.com/65704439/210285096-923becf6-51a8-4f1b-a7dd-1dcd4d7d45a5.png)

**Comment by ArtpokeBr** [comment]
Are you sure this isn't an issue with your installation?

**Comment by KydZombie** [comment]
All the files are the same on my end too, which is why I reported it here.

**Comment by ArtpokeBr** [comment]
Did you update to the most recent version aswell?

**Comment by KydZombie** [comment]
Currently doing so, as I noticed that there was a new version just now

**Comment by KydZombie** [comment]
Just reinstalled the pack completely. Did not fix it.

**Comment by KydZombie** [comment]
Getting this error in the log:
`[18:05:32] [Client thread/ERROR] [FML]: Exception loading model for variant contenttweaker:searedplate#inventory, normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model contenttweaker:item/searedplate with loader VanillaLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:161) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.loadItemModels(ModelLoader.java:302) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadVariantItemModels(ModelBakery.java:175) ~[cgb.class:?]
	at net.minecraftforge.client.model.ModelLoader.setupModelRegistry(ModelLoader.java:151) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.onResourceManagerReload(ModelManager.java:28) [cgc.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121) [cev.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:513) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:5101) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_352]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_352]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_352]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_352]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.io.FileNotFoundException: contenttweaker:models/item/searedplate.json
	at net.minecraft.client.resources.FallbackResourceManager.getResource(FallbackResourceManager.java:69) ~[cei.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.getResource(SimpleReloadableResourceManager.java:65) ~[cev.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadModel(ModelBakery.java:334) ~[cgb.class:?]
	at net.minecraftforge.client.model.ModelLoader.access$1400(ModelLoader.java:115) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:861) ~[ModelLoader$VanillaLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:157) ~[ModelLoaderRegistry.class:?]
	... 17 more`

**Comment by ArtpokeBr** [comment]
This is truly something i've never saw, I'll have to investigate further when possible.

But another thing, how much RAM you have allocated and are you playing on Linux?

**Comment by KydZombie** [comment]
6GB, and yes I am on Linux.

**Comment by ArtpokeBr** [comment]
Ok, I think I have an Idea of what I can do.

**Comment by ArtpokeBr** [comment]
Just to clarify what is happening, essentially Linux is an Case Sensitive Enviroment, and all of those items that are missing textures use rely on Windows not being Case Sensitive to work.

What this means is that I need to edit my source code for them and edit the ones that are erroring. this is the full list of items that you've found right? I can work on it, Idk when, but now that I know what needs to be done, it shouldn't take a while.

**Comment by ArtpokeBr** [comment]
Ok, Nvm. Fixed the ones that you've mentioned, please, if there's more, tell me ;)

**Comment by KydZombie** [comment]
This is supposed to be fixed on beta 1.9 right? Because I don't see any change to the broken items

**Comment by ArtpokeBr** [comment]
> This is supposed to be fixed on beta 1.9 right? Because I don't see any change to the broken items

You don't? Well, this is weird

**Comment by KydZombie** [comment]
Any update?

**Comment by ArtpokeBr** [comment]
The only thing related to this issue that i've found here while working on the next patch, was the mason blocks textures not working as intended, i've changed their ID's in order to make it work for Linux Users and forgot to rename the textures themselves.

**Comment by ArtpokeBr** [comment]
You said that all the items/blocks listed above are still not working right?

**Comment by KydZombie** [comment]
It no longer has the weird text with the model info, so the model itself is probably working but it can't find the texture somehow
![image](https://user-images.githubusercontent.com/65704439/213924903-89bde6b7-40c4-4cfa-b04b-7147f8c47155.png)

**Comment by ArtpokeBr** [comment]
This is is indeed very weird, currently on a vacation so I won't be able to investigate more.

Thx for the patience btw. =)
